version: 2
builds:
  - id: box
    dir: .
    main: ./cmd/gpp/main.go
    binary: gpp-server
    ldflags: -s -w
    flags:
      - -tags=with_quic
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64