name: releaser
on:
  push:
    branches:
      - 'dev'
    tags:
      - 'v*'
env:
  #对于大多数环境都是必需的，因为由于OOM问题可能会发生构建失败
  NODE_OPTIONS: "--max-old-space-size=4096"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  wails:
    # 一个平台构建的失败不会影响其他平台
    fail-fast: false
    matrix:
      build:
        - name: 'App'
          platform: 'linux/amd64'
          os: 'ubuntu-latest'
        - name: 'App'
          platform: 'windows/amd64'
          os: 'windows-latest'
        - name: 'App'
          platform: 'darwin/universal'
          os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22'